INSERT INTO products (code, name, description, image_url, price) VALUES
    ('BOOK001', 'The Art of Code', 'A deep dive into the philosophy of clean code.', 'https://example.com/image1.jpg', 25.99),
    ('BOOK002', 'Java Spring Boot in Action', 'Comprehensive guide to Spring Boot development.', 'https://example.com/image2.jpg', 29.50),
    ('BOOK003', 'Mastering PostgreSQL', 'Become a PostgreSQL expert.', 'https://example.com/image3.jpg', 27.75),
    ('BOOK004', 'Python for Everyone', 'An accessible introduction to Python.', 'https://example.com/image4.jpg', 24.00),
    ('BOOK005', 'JavaScript: The Definitive Guide', 'Deep dive into JavaScript.', 'https://example.com/image5.jpg', 32.10),
    ('BOOK006', 'HTML & CSS Design', 'Basics of web design and layout.', 'https://example.com/image6.jpg', 21.99),
    ('BOOK007', 'React Explained', 'Understanding React from the ground up.', 'https://example.com/image7.jpg', 26.00),
    ('BOOK008', 'Kotlin for Android Developers', 'Build Android apps with Kotlin.', 'https://example.com/image8.jpg', 28.40),
    ('BOOK009', 'Design Patterns Uncovered', 'A guide to reusable software patterns.', 'https://example.com/image9.jpg', 31.00),
    ('BOOK010', 'Agile Project Management', 'Principles and practices of agile.', 'https://example.com/image10.jpg', 19.99),
    ('BOOK011', 'Docker Deep Dive', 'Mastering containerization.', 'https://example.com/image11.jpg', 27.30),
    ('BOOK012', 'Microservices Architecture', 'Building scalable services.', 'https://example.com/image12.jpg', 30.50),
    ('BOOK013', 'Git Essentials', 'Version control for developers.', 'https://example.com/image13.jpg', 18.75),
    ('BOOK014', 'Data Structures in Java', 'Classic data structures and algorithms.', 'https://example.com/image14.jpg', 29.90),
    ('BOOK015', 'DevOps Handbook', 'Accelerate your DevOps journey.', 'https://example.com/image15.jpg', 33.25),
    ('BOOK016', 'Machine Learning Basics', 'Introductory ML concepts.', 'https://example.com/image16.jpg', 34.99),
    ('BOOK017', 'Neural Networks Explained', 'Fundamentals of neural networks.', 'https://example.com/image17.jpg', 38.00),
    ('BOOK018', 'Rust Programming Guide', 'Fast and safe systems programming.', 'https://example.com/image18.jpg', 30.25),
    ('BOOK019', 'Effective TypeScript', 'Writing better TypeScript code.', 'https://example.com/image19.jpg', 28.00),
    ('BOOK020', 'Fullstack Development with Node.js', 'Building apps from front to back.', 'https://example.com/image20.jpg', 29.95),
    ('BOOK021', 'SQL for Data Analysis', 'Querying and analyzing data.', 'https://example.com/image21.jpg', 26.99),
    ('BOOK022', 'Cloud Native Apps', 'Deploying applications in the cloud.', 'https://example.com/image22.jpg', 32.00),
    ('BOOK023', 'The Pragmatic Programmer', 'Classic software engineering insights.', 'https://example.com/image23.jpg', 34.50),
    ('BOOK024', 'You Don’t Know JS', 'Exploring JavaScript deeply.', 'https://example.com/image24.jpg', 22.75),
    ('BOOK025', 'Linux Command Line', 'Master the shell.', 'https://example.com/image25.jpg', 19.85),
    ('BOOK026', 'Vue.js Up and Running', 'Get started with Vue.js.', 'https://example.com/image26.jpg', 24.60),
    ('BOOK027', 'Cybersecurity 101', 'Basics of staying secure online.', 'https://example.com/image27.jpg', 23.40),
    ('BOOK028', 'Android App Development', 'Create mobile apps from scratch.', 'https://example.com/image28.jpg', 27.80),
    ('BOOK029', 'CI/CD Pipelines', 'Automate your software delivery.', 'https://example.com/image29.jpg', 29.10),
    ('BOOK030', 'Scrum Essentials', 'Delivering value through Scrum.', 'https://example.com/image30.jpg', 21.25),
    ('BOOK031', 'AI Ethics', 'Understanding the ethics of AI.', 'https://example.com/image31.jpg', 25.75),
    ('BOOK032', 'Jenkins in Practice', 'Continuous integration with Jenkins.', 'https://example.com/image32.jpg', 26.20),
    ('BOOK033', 'Terraform Infrastructure as Code', 'Automate cloud deployments.', 'https://example.com/image33.jpg', 33.00),
    ('BOOK034', 'Blockchain for Developers', 'Building decentralized apps.', 'https://example.com/image34.jpg', 36.40),
    ('BOOK035', 'PHP Modern Development', 'Writing clean PHP.', 'https://example.com/image35.jpg', 20.50),
    ('BOOK036', 'Data Visualization with D3.js', 'Craft stunning charts.', 'https://example.com/image36.jpg', 28.85),
    ('BOOK037', 'C# Programming Masterclass', 'Learn modern C#.', 'https://example.com/image37.jpg', 29.60),
    ('BOOK038', 'Testing Java Applications', 'Unit and integration testing.', 'https://example.com/image38.jpg', 30.99),
    ('BOOK039', 'Intro to GraphQL', 'Powerful APIs with GraphQL.', 'https://example.com/image39.jpg', 27.20),
    ('BOOK040', 'Big Data Fundamentals', 'Learn big data technologies.', 'https://example.com/image40.jpg', 35.10);
