version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yml"

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: "Run code formatter then run tests"
    deps: [format]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    desc: "Format code using Spotless"
    cmds:
      - "{{.MVNW}} spotless:apply"

  build:
    desc: "Build the project without running tests"
    deps: [format]
    cmds:
      - "{{.MVNW}} -pl catalog-service spring-boot:build-image -DskipTests"

  start_infra:
    desc: "Start Docker Compose infrastructure services"
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} up -d"

  stop_infra:
    desc: "Stop and remove Docker Compose infrastructure services"
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} down"

  restart_infra:
    desc: "Restart Docker Compose infrastructure services"
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  start:
    desc: "Start Docker Compose infrastructure and application services"
    deps: [build]
    cmds:
      - task: stop
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} up -d"

  stop:
    desc: "Stop and remove Docker Compose infrastructure  and application services"
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} down"

  restart:
    desc: "Restart Docker Compose infrastructure and application services"
    cmds:
      - task: stop
      - |
        {{if eq OS "windows"}}
          timeout /T 5 /NOBREAK
        {{else}}
          sleep 5
        {{end}}
      - task: start

  sleep:
    internal: true
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - sleep {{.DURATION}}